Project InventorySystem {
  orm:'eloquent'
  database_type: 'PostgreSQL'
  Note: 'Sistema de Inventario Robusto con preparación para POS y Facturación'
}

// ---------------------------------------------------------
// 1. CATÁLOGOS Y DATOS MAESTROS
// ---------------------------------------------------------

Table users {
  id unsignedbigint [primary key, increment]
  name varchar(100) [not null]
  email varchar(100) [not null]
  email_verified_at timestamp [null]
  password varchar(255) [not null]
  created_at timestamp [not null]
  updated_at timestamp [not null]
  is_active boolean [default: true]

  Note: 'Usuarios del sistema'
}

Table warehouses {
  id unsignedbigint [primary key, increment]
  parent_id unsignedbigint [null, note: 'Para sucursales dentro de una misma empresa']
  name varchar [not null, note: 'Nombre de la sucursal o bodega']
  description varchar(255) [null, note: 'Descripción adicional']
  address varchar(255) [not null, note: 'Dirección del almacén o tienda']
  departament varchar(50) [null, note: 'Departamento o Región']
  province varchar(50) [null, note: 'Provincia']
  district varchar(50) [null, note: 'Distrito']
  ubigueo varchar(6) [null, note: 'Código UBIGEO']
  created_at timestamp [not null, note: 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [not null, note: 'Fecha de última actualización del registro en la base de datos'] 
  is_active boolean [default: true, note: 'Si es false, no aparece en el selector al crear documentos']

  Note: 'Bodegas físicas o Tiendas (Puntos de Venta)'
}

Table suppliers {
  id unsignedbigint [primary key, increment]
  trade_name varchar(100) [null, note: 'Nombre comercial']
  company_name varchar(100) [null, note: 'Razón social']
  ruc varchar(15) [not null, note: 'Número RUC']
  contact_name varchar(100) [not null, note: 'Nombre del contacto principal dentro de la empresa']
  email varchar(100) [null, note: 'Correo electrónico de contacto']
  phone varchar(100) [not null, note: 'Teléfono de contacto']
  address text(100) [not null, note: 'Dirección física de la empresa']
  departament varchar(50) [not null, note: 'Departamento o Región']
  province varchar(50) [not null, note: 'Provincia']
  district varchar(50) [not null, note: 'Distrito']
  ubigueo varchar(6) [not null, note: 'Código UBIGEO']
  created_at timestamp [not null, note: 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [not null, note: 'Fecha de última actualización del registro en la base de datos']
  is_active boolean [default: true,note: "si es false, no aparece en el selector al crear documentos"]
  

  Note: 'Proveedores de productos y servicios'
}

Table customers {
  id unsignedbigint [primary key, increment]
  names varchar(100) [not null, note: 'Nombres del cliente']
  first_surname varchar(50) [null, note: 'Primer apellido']
  second_surname varchar(50) [null, note: 'Segundo apellido']
  id_document_number varchar(20) [null, note: 'Número de documento de identifiación']
  ruc varchar(15) [null, note: 'RUC para empresas']
  email varchar(100) [null, note: 'Correo electrónico del cliente']
  phone varchar(50) [null, note: 'Teléfono del cliente']
  address text(100) [null, note: 'Dirección del cliente']
  departament varchar(50) [null, note: 'Departamento del cliente']
  province varchar(50) [null, note: 'Provincia del cliente']
  district varchar(50) [null, note: 'Distrito del cliente']
  ubigueo varchar(6) [null, note: 'Código UBIGEO']
  created_at timestamp [not null, note: 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [not null, note: 'Fecha de última actualización del registro en la base de datos']
  is_active boolean [default: true]

  Note: 'Clientes para ventas y facturación'
}


Table sunat_catalogs {
  id unsignedbigint [primary key, increment]
  number varchar(10) [note: 'Número de catalógo SUNAT, Ej: 01, 02, 03']
  description varchar(255) [note: 'Descripción del catálogo SUNAT']
  created_at timestamp [not null, note: 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [not null, note: 'Fecha de última actualización del registro en la base de datos']
}

Table sunat_codes {
  id unsignedbigint [primary key, increment]
  sunat_catalog_id unsignedbigint [note: 'Referencia a la tabla sunat_catalogs']
  code varchar(10) [note: 'Código del ítem en el catálogo SUNAT']
  description varchar(255) [note: 'Descripción del ítem en el catálogo SUNAT']
  short_description varchar(100) [note: 'Descripción corta para mostrar en UI']
  created_at timestamp [not null, note: 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [not null, note: 'Fecha de última actualización del registro en la base de datos']
}

Table movement_types {
  id unsignedbigint [primary key, increment]
  name varchar [note: 'Ej: Compra, Venta, Ajuste Entrada y Ajuste Salida']
  action enum('input', 'output') [note: 'Define si suma o resta matemáticamente (input: suma, output: resta)']
  created_at timestamp [note: 'Fecha de creación del registro en la base de datos']
}

Table categories {
  id unsignedbigint [primary key, increment]
  name varchar(100) [not null, note: 'Nombre de la categoría']
  description varchar(255) [null, note: 'Descripción adicional de la categoría']
  parent_id unsignedbigint [note: 'Referencia a la misma tabla categories para subcategorías']
  is_active boolean [default: true, note: 'Si es false, no aparece en el selector al crear productos']
  created_at timestamp [not null, note: 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [not null, note: 'Fecha de última actualización del registro en la base de datos']
}

Table brands {
  id unsignedbigint [primary key, increment]
  name varchar(50) [note: 'Toyota, Hyunday, Repsol, Pari']
  created_at timestamp [not null, note: 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [not null, note: 'Fecha de última actualización del registro en la base de datos']
}

Table sales_origins {
  id unsignedbigint [primary key, increment]    
  name varchar(30) [note: 'Ej: POS, APP, WEB, etc.']
  description varchar(255) [null, note: 'Descripción adicional del origen de la venta']
  is_active boolean [default: true]
}

Table payment_methods{
  id unsignedbigint [primary key, increment]    
  name varchar(50) [note: 'Ej: Efectivo, Tarjeta de Crédito, Yape, Plin']
  extra_charge decimal(5,2) [default: 0, note: 'Porcentaje extra por uso del método de pago (Ej: 2.50 para 2.5%)']
  is_fixed_charge boolean [default: false, note: 'True si el cargo extra es un monto fijo en lugar de un porcentaje']
  description varchar(255) [null, note: 'Descripción adicional del método de pago']
  is_active boolean [default: true]
}

// ---------------------------------------------------------
// 2. PRODUCTOS 
// ---------------------------------------------------------

Table products {
  id unsignedbigint [primary key, increment]
  sku varchar(50) [unique, not null, note: 'Código interno único']
  barcode varchar(70) [note: 'Código EAN/UPC escaneable']
  name varchar(100) [not null, note: 'Nombre del producto']
  description varchar(255) [null, note: 'Descripción del producto']

  brand_id unsignedbigint [null, note: 'Referencia a la tabla brands']
  category_id unsignedbigint [not null,note: 'Referencia a la tabla categories']
  unit_id unsignedbigint [not null, note: 'Referencia a la tabla units_of_measure']

  images json [null, note: 'Array JSON con URLs de imágenes del producto']
  
  // Precios y Costos promedios
  net_amount decimal(10,2) [note: 'Precio neto, sin impuestos']
  average_cost decimal(15,4) [default: 0, note: 'Costo Promedio Ponderado Global (Referencial)']

  // Configuraciones
  min_stock integer [default: 2, note: 'Punto de reorden']
  alert_stock boolean [default: true, note: 'True para activar alerta de stock bajo']
  is_inventoriable boolean [default: true, note: 'False para servicios']

  created_at timestamp [not null, note: 'Fecha de creación del registro en la base de datos']
  deleted_at timestamp [null, note: 'Soft Delete']
}

// ---------------------------------------------------------
// 3. STOCK (FOTO ACTUAL)
// ---------------------------------------------------------

Table product_warehouse {
  id unsignedbigint [primary key, increment]
  warehouse_id unsignedbigint [note: 'Referencia a la tabla warehouses']
  product_id unsignedbigint [note: 'Referencia a la tabla products']
  available_stock decimal(10,2) [default: 0, note: 'Stock disponible para venta']
  real_stock decimal(10,2) [default: 0, note: 'Stock físico en bodega']
  created_at timestamp [note: 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [note: 'Fecha de última actualización del registro en la base de datos']

  Note: 'Tabla snapshot. Debe coincidir con la suma del Kardex'
}

// ---------------------------------------------------------
// 4. KARDEX (HISTORIAL DE MOVIMIENTOS)
// ---------------------------------------------------------

Table kardex {
  id unsignedbigint [primary key, increment]
  date timestamp [note: 'Fecha de generación del movimiento']
  
  // Ubicación y Producto
  warehouse_id unsignedbigint [note: 'Referencia a la tabla warehouses, id del warehouse donde ocurre la acción']
  product_id unsignedbigint [note: 'Referencia a la tabla products, id del producto afectado']
  movement_type_id unsignedbigint [note: 'Referencia a la tabla movement_types, define si es entrada o salida (+ o -)']
  
  // Polimorfismo (La clave del sistema)
  related_doc_type varchar(100) [note: 'Almacena la ruta del modelo para una relación polimórfica (usando "ELOQUENT") Ej: "\App\PurchaseOrder" o "\App\SalesOrder"']
  related_doc_id unsignedbigint [note: 'Referencia al id del registro en el modelo relacionado)']

  // Valores matemáticos del movimiento
  quantity decimal(15,4) [note: 'Cantidad movida (+ o -)']
  unit_cost decimal(15,4) [note: 'Costo unitario por item al momento del registro, sin ninguna impuestos (precio neto)']
  total_cost decimal(15,4) [note: 'quantity * unit_cost']
  
  // Saldos resultantes (Para auditoría rápida)
  stock_balance decimal(15,4) [note: 'Stock despues del movimiento: stock anterior +/- quantity']
  average_cost_balance decimal(15,4) [note: 'Nuevo Costo Promedio después del movimiento: (solo si es entrada(+) de inventario)']
  
  created_at timestamp [note: 'Fecha de creación del registro en la base de datos']
  created_by unsignedbigint [note: 'Referencia a la tabla users,id del usuario que provocó el movimiento']

  indexes {
    (product_id, warehouse_id) [name: 'kardex_product_warehouse_idx']
    (related_doc_type, related_doc_id) [name: 'kardex_polymorphic_idx']
    date [name: 'kardex_date_idx']
  }
}

// ---------------------------------------------------------
// 5. DOCUMENTO DE SISTEMA: ORDEN DE COMPRA (ENTRADAS)
// ---------------------------------------------------------

Table purchase_orders {
  id unsignedbigint [primary key, increment]
  supplier_id unsignedbigint [note: 'Referencia a la tabla suppliers']
  warehouse_id unsignedbigint [note: 'A dónde entra la mercancía']
  date timestamp [note: 'Fecha de generación de la orden de compra'] 
  status enum('draft', 'ordered', 'partial','delivered', 'cancelled')
  payment_status enum('unpaid', 'partial', 'paid') [note: 'Estado del pago de la orden de compra']

  scheduled_delivery_date timestamp [null, note: 'Fecha estimada de entrega por parte del proveedor']
  delivery_deadline timestamp [null, note: 'Fecha límite acordada para la entrega']

  supplier_invoice_number varchar [note: 'El folio de la factura del proveedor']
  total_amount decimal(12,2) [note: 'Monto total de la orden de compra']
  notes text [null, note: 'Notas adicionales sobre la orden de compra']
  
  created_by unsignedbigint [not null, note: 'Id de usuario que creó la orden de compra']
  created_at timestamp [not null, note: 'Fecha de registro de la orden de compra en la base de datos']
}

Table purchase_items {
  id unsignedbigint [primary key, increment]
  purchase_order_id unsignedbigint [null, note: 'Referencia a la tabla purchase_orders']
  product_id unsignedbigint [null,note: 'Referencia a la tabla products']
  quantity decimal(10,2) [note: 'Cantidad de producto']
  actual_delivery_date timestamp [null, note: 'Fecha real de recepción del producto']
  entered_price decimal(15,4) [note: 'Precio digitado por el usuario']
  tax_included boolean [default:false, note: 'True si el precio incluye impuestos'] 
  calculated_net_cost decimal(15,4) [note: 'Costo neto calculado (sin impuestos)'] 
  total_item_net decimal(15,4) [note: 'calculated_net_cost * quantity']
}

Table purchase_item_tax {
  id unsignedbigint [primary key, increment]
  purchase_item_id unsignedbigint [note: 'Referencia a la tabla purchase_items'] 
  tax_id unsignedbigint [note: 'Referencia a la tabla taxes'] 
  
  tax_rate decimal(5,2) [note: 'Copia de la tasa en el momento de la compra'] 
  tax_amount decimal(15,4) [note: 'Monto de dinero de este impuesto para este item'] 

  note: 'Tabla pivote para relación muchos a muchos entre las tablas purchase_items y taxes'
}

Table invoices_purchases{
  id unsignedbigint [primary key,increment]
  series varchar(20) [note: 'Ej: F001']
  number varchar(20) [note: 'Ej: 000045']
  date timestamp [note: 'Fecha de emisión']
  supplier_id unsignedbigint [note: 'Referencia a la tabla suppliers']
  net_amount decimal(15,4) [note: 'Monto neto de la factura']
  tax_amount decimal(15,4) [note: 'Monto total de impuestos']
  total_amount decimal(15,4) [note: 'Monto total de la factura']
  status enum('draft', 'issued', 'paid', 'cancelled') [default: 'issued']
  created_by unsignedbigint [note: 'Referencia a la tabla users, id del usuario que creó la factura']
  created_at timestamp [note: 'Fecha de registro de la factura en la base de datos']
}

Table invoices_purchases_items{
  id unsignedbigint [primary key, increment]
  invoice_purchase_id unsignedbigint [note: 'Referencia a la tabla invoices_purchases']
  product_id unsignedbigint [note: 'Referencia a la tabla products']
  quantity decimal(10,2) [note: 'Cantidad comprada']
  net_amount decimal(12,2) [note: 'Precio neto al momento']
  tax_amount decimal(12,2) [note: 'Monto total de impuestos para este ítem']
  total_amount decimal(12,2) [note: 'Precio total (quantity * (tax_amount + net_amount))']
  created_at timestamp [note: 'Fecha de registro del ítem en la base de datos'] 
  }

// ---------------------------------------------------------
// 6. DOCUMENTO DE SISTEMA: ORDEN DE VENTA (SALIDAS)
// ---------------------------------------------------------

Table sales_orders {
  id unsignedbigint [primary key, increment]
  customer_id unsignedbigint [note: 'Referencia a la tabla customers']  
  warehouse_id unsignedbigint [note: 'Referencia a la tabla warehouses']
  sale_origin_id unsignedbigint [note: 'Referencia a la tabla sales_origins, Ej: POS, APP, WEB'] 

  // estados de venta y pago   
  status enum('pending', 'completed', 'cancelled', 'returned') [note: 'Estado de la venta']
  payment_status enum('unpaid', 'partial', 'paid') [note: 'Estado del pago']

  // Datos Financieros (Facturación)
  subtotal decimal(12,2) [note: 'Subtotal de la venta']
  payment_surcharge decimal(12,2) [default: 0, note: 'Cargo adicional por método de pago']
  tax_amount decimal(12,2) [note: 'Monto total de impuestos']
  total_amount decimal(12,2) [note: 'Total de la venta (subtotal + impuestos + cargos)']

  invoice_series varchar(20) [note: 'Ej: F001']
  invoice_number varchar(20) [note: 'Ej: 000045']
  
  created_by unsignedbigint [note: 'Id de usuario que realizó la venta']
  
  // Hitos de vida de la venta
  cacelled_at timestamp [null, note: 'Fecha de cancelación de la venta']
  paid_at timestamp [null, note:'Fecha de pago']
  delivered_at timestamp [null, note: 'Fecha de entrega del producto']
  

  created_at timestamp [not null, note: 'Fecha de registro de la venta en la base de datos']
}

Table sales_items {
  id unsignedbigint [primary key, increment]
  sales_order_id unsignedbigint [note: 'Referencia a la tabla sales_orders']
  product_id unsignedbigint [note: 'Referencia a la tabla products']
  quantity decimal(10,2) [note: 'Cantidad vendida']
  unit_amount decimal(12,2) [note: 'Precio de venta al momento']
  total_amount decimal(12,2)
  
  // Importante para margen de ganancia
  cost_at_moment decimal(15,4) [note: 'Se copia del average_cost del producto al vender']
}

Table sales_item_tax {
  id unsignedbigint [primary key, increment]
  sales_item_id unsignedbigint
  tax_id unsignedbigint
  tax_rate decimal(5,2)
  tax_amount decimal(15,4)
}

Table invoices_sales{
  id unsignedbigint [primary key,increment]
  series varchar(20) [note: 'Ej: F001']
  number varchar(20) [note: 'Ej: 000045']

  invoiceable_type varchar(100) [null, note: 'Almacena la ruta del modelo para una relación polimórfica (usando "ELOQUENT") Ej: "\App\SalesOrder" o "\App\SomeOtherModel"']
  invoiceable_id unsignedbigint [null, note: 'Referencia al id del registro en el modelo relacionado)']

  date timestamp [note: 'Fecha de emisión']
  customer_id unsignedbigint [note: 'Referencia a la tabla customers']
  total_amount decimal(15,4) [note: 'Monto total de la factura']
  status enum('draft', 'issued', 'paid', 'cancelled') [default: 'draft']

  sunat_status enum('pending', 'accepted', 'rejected', 'error') [default: 'pending', note: 'Estado del envío a SUNAT']
  sunat_response_raw json [null, note: 'Código de respuesta de SUNAT tras el envío']

  cdr_path text [null, note: 'Ruta al archivo CDR recibido de SUNAT']
  xml_path text [null, note: 'Ruta al archivo XML de la factura electrónica']
  pdf_path text [null, note: 'Ruta al archivo PDF de la factura para impresión']

  created_by unsignedbigint [note: 'Referencia a la tabla users, id del usuario que creó la factura']
  created_at timestamp [note: 'Fecha de registro de la factura en la base de datos']
}

Table invoices_sales_items{
  id unsignedbigint [primary key, increment]
  invoice_sale_id unsignedbigint [note: 'Referencia a la tabla invoices_sales']
  product_id unsignedbigint [note: 'Referencia a la tabla products']
  quantity decimal(10,2) [note: 'Cantidad vendida']
  net_amount decimal(12,2) [note: 'Precio de venta al momento']
  tax_amount decimal(12,2) [note: 'Monto total de impuestos para este ítem']
  total_amount decimal(12,2) [note: 'Precio total (quantity * (tax_amount + net_amount))']
  created_at timestamp [note: 'Fecha de registro del ítem en la base de datos']
}

// ---------------------------------------------------------
// 7. DOCUMENTO DE SISTEMA: ORDEN DE TRASLADO INTERNO (MOVIMIENTO INTERNO)
// ---------------------------------------------------------

Table internal_transfer_order {
  id unsignedbigint [primary key, increment]
  from_warehouse_id unsignedbigint [note: 'Referencia a la tabla warehouses (origen)']
  to_warehouse_id unsignedbigint [note: 'Referencia a la tabla warehouses (destino)']
  date timestamp [note: 'Fecha de la creación del traslado']
  reason varchar(255) [null,note: 'Motivo del traslado']
  status enum('draft', 'in_transit', 'completed', 'cancelled')
  created_by unsignedbigint [note: 'Id de usuario que creó el traslado']
  created_at timestamp [note: 'Fecha de registro en la base de datos']
}

Table internal_transfers_item {
  id unsignedbigint [primary key, increment]
  internal_transfer_id unsignedbigint [note: 'Referencia a la tabla internal_transfers']
  product_id unsignedbigint [note: 'Referencia a la tabla products']
  quantity decimal(10,2) [note: 'Cantidad a trasladar']
  unit_amount decimal(12,2) [note: 'Precio de venta al momento']
  tax_amount decimal(12,2) [note: 'Monto total de impuestos para este ítem']
  total_amount decimal(12,2) [note: 'Precio total (quantity * (tax_amount + unit_amount))']
}

// ---------------------------------------------------------
// 8. DOCUMENTO DE SISTEMA: AJUSTES MANUALES (MOVIMIENTO MANUAL DE INVENTARIO)
// ---------------------------------------------------------

Table inventory_adjustments {
  id unsignedbigint [primary key, increment]
  warehouse_id unsignedbigint
  reason varchar [note: 'Ej: Merma, Robo, Conteo Inicial']
  date timestamp
  status enum('draft', 'applied', 'cancelled')
  created_by unsignedbigint [note: 'Referencia a la tabla users, id del usuario que creó el ajuste']
  created_at timestamp [note: 'Fecha de registro del ajuste en la base de datos']
}

Table inventory_adjustment_items {
  id unsignedbigint [primary key, increment]
  adjustment_id unsignedbigint [note: 'Referencia a la tabla inventory_adjustments']
  product_id unsignedbigint [note: 'Referencia a la tabla products']
  current_stock decimal(10,2) [note: 'Stock antes del ajuste']
  adjusted_quantity decimal(10,2) [note: 'Cantidad a sumar/restar']
}

// ---------------------------------------------------------
// 9. IMPUESTOS
// ---------------------------------------------------------

Table tax_product {
  id unsignedbigint [primary key, increment]
  product_id unsignedbigint [not null, note: 'Referencia a la tabla products']
  tax_id unsignedbigint [not null, note: 'Referencia a la tabla sunat_codes, id del impuesto aplicado al producto']
  note: 'Tabla pivote para relación muchos a muchos entre productos e impuestos'
}


// ---------------------------------------------------------
// 11. CAJAS REGISTRADORAS (Y TURNOS DE CAJA)
// ---------------------------------------------------------

Table cash_registers {
  id unsignedbigint [primary key, increment]
  
  // Ubicación
  warehouse_id unsignedbigint [note: 'A qué sucursal pertenece (Ej: Tienda Juliaca)']
  
  // Identificación
  name varchar(100) [note: 'Ej: Caja Rápida 1, Caja Principal, Tablet Vendedor 3']
  code varchar(50) [unique, note: 'Código de activo fijo o serie interna (Ej: POS-JUL-01)']
  
  // Estado y Optimización
  is_active boolean [default: true, note: 'Si es false, no aparece en el selector al iniciar sesión']
  internal_note text [null, note: 'Notas internas sobre la caja registradora (Ej: Ubicación física, tipo de impresora, falla conocida, etc.)']
  
  // CACHÉ DE RENDIMIENTO (El truco del Senior Dev)
  // Guarda el ID del turno actual para no buscarlo en la tabla gigante de shifts en cada venta.
  current_shift_id unsignedbigint [null, note: 'Si es NULL = Caja Cerrada. Si tiene ID = Caja Ocupada.']

  // Configuración Técnica Local
  settings json [null, note: 'IP de impresora, footer del ticket, si permite pagos en dólares, etc.']
  
  created_at timestamp [not null, note : 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [not null, note : 'Fecha de última actualización del registro en la base de datos']
}


Table cash_register_shifts {
  id unsignedbigint [primary key, increment]
  
  // Relaciones (Quién y Dónde)
  cash_register_id unsignedbigint [note: 'Referencia a la tabla cash_registers, id de la caja registradora']
  user_id unsignedbigint [note: 'Referencia a la tabla users, id del cajero responsable']
  
  // Tiempos y Estado
  status enum('close', 'open', 'auditing') [default: 'open', note: 'Estados: open, closed, auditing (bloqueado para conteo)']
  opened_at timestamp [not null, note: 'Fecha y hora de apertura del turno']
  closed_at timestamp [null, note: 'Fecha y hora de cierre del turno']
  
  // DINERO INICIAL (Base/Sencillo)
  starting_cash decimal(15,4) [default: 0, note: 'Dinero entregado al cajero al iniciar para dar vuelto']
  
  // --- SECCIÓN A: LO QUE DICE EL SISTEMA (Calculado) ---
  // Estos campos se llenan solos sumando la tabla 'payments' al cerrar.
  system_cash_sales decimal(15,4) [default: 0, note: 'Total ventas en Efectivo según software']
  system_card_sales decimal(15,4) [default: 0, note: 'Total ventas Tarjeta según software']
  system_transfer_sales decimal(15,4) [default: 0]
  system_expenses decimal(15,4) [default: 0, note: 'Salidas de dinero registradas (Ej: Pago a proveedores caja chica)']
  
  // --- SECCIÓN B: LO QUE DICE EL CAJERO (Realidad) ---
  // Estos campos los llena el humano contando billete por billete.
  real_cash_count decimal(15,4) [null]
  real_card_count decimal(15,4) [null, note: 'Suma de vouchers físicos']
  
  // --- SECCIÓN C: EL VEREDICTO ---
  // Diferencia = (Real - (Inicial + VentasSistema - Gastos))
  difference decimal(15,4) [null, note: '0 = Perfecto. Negativo = Faltante (Robo/Error). Positivo = Sobrante.']
  
  closing_note text [null, note: 'Explicación del cajero si hubo diferencia']
  
  created_at timestamp
  updated_at timestamp
}

// ---------------------------------------------------------
// 12. GUÍAS DE REMISIÓN (REMITENTE Y TRANSPORTISTA)
// ---------------------------------------------------------
Table referral_guides{
  id unsignedbigint [primary key, increment]

  transmitter_id unsignedbigint [note: 'Referencia a la tabla suppliers o company_settings, dependiendo si somos vendedores o compradores']
  receiver_id unsignedbigint [note: 'Referencia a la tabla customers o company_settings, dependiendo si somos vendedores o compradores']
  movement_type_id unsignedbigint [note: 'Referencia a la tabla movement_types, define si es entrada o salida (+ o -)']

  purchase_order_id unsignedbigint [null, note: 'Referencia a la tabla purchase_orders, id de la orden de compra asociada (si aplica)']
  sale_order_id unsignedbigint [null, note: 'Referencia a la tabla sale_orders, id de la orden de venta asociada (si aplica)']
  internal_transfer_id unsignedbigint [null, note: 'Referencia a la tabla internal_transfer_order, id de la orden de traslado interno asociada (si aplica)']

  // INFORMACIÓN DE LA GUÍA
  type_of_referral_guide enum('remitter', 'carrier') [note: 'Tipo de guía de remisión']
  transport_mode enum('own_transport', 'third_party') [note: 'Modo de transporte utilizado']
  number_of_packages integer [null, note: 'Número de bultos o paquetes transportados']
  series varchar(20) [not null, note: 'Ej: GR001']
  number varchar(20) [not null, note: 'Ej: 000123']
  gross_total_weight decimal(10,2) [null, note: 'Peso bruto de la mercancía (kg)']
  net_total_weight decimal(10,2) [null, note: 'Peso neto de la mercancía (kg)']
  issue_date timestamp [not null, note: 'Fecha de emisión de la guía de remisión']
  transfer_start_date timestamp [not null, note: 'Fecha de inicio del traslado']
  transfer_end_date timestamp [not null, note: 'Fecha de finalización del traslado']

  // INFORMACIÓN DEL EMISOR
  origin_address varchar(255) [note: 'Dirección de origen, se puede copiar de la dirección del proveedor']
  origin_departament varchar(50) [null, note: 'Departamento de origen, se puede copiar del departamento del proveedor']
  origin_province varchar(50) [null, note: 'Provincia de origen, se puede copiar de la provincia del proveedor']
  origin_district varchar(50) [null, note: 'Distrito de origen, se puede copiar del distrito del proveedor']


  // INFORMACIÓN DEL RECEPTOR
  destination_address varchar(255) [note: 'Dirección de destino, se puede copiar de la dirección de la sucursal']
  destination_departament varchar(50) [null, note: 'Departamento de destino, se puede copiar del departamento de la sucursal']
  destination_province varchar(50) [null, note: 'Provincia de destino, se puede copiar de la provincia de la sucursal']
  destination_district varchar(50) [null, note: 'Distrito de destino, se puede copiar del distrito de la sucursal']
 
  net_amount decimal(12,2) [note: 'Valor total de la mercancía sin impuestos']
  total_tax decimal(12,2) [note: 'Monto total de impuestos aplicados']
  total_amount decimal(12,2) [note: 'Valor total de la guía de remisión (net_amount + total_tax)']
  
  
  // DETALLES DEL TRANSPORTE
  transporter_name varchar(100) [not null, note: 'Nombre de la empresa transportista (si aplica)']
  driver_name varchar(100) [null, note: 'Nombre del conductor (si aplica)']
  vehicle_plate varchar(20) [null, note: 'Placa del vehículo utilizado para el transporte']
  vehicle_details varchar(255) [null, note: 'Detalles del vehículo (si aplica)']

  created_by unsignedbigint [note: 'Referencia a la tabla users, id del usuario que creó la guía de remisión']
  created_at timestamp [note: 'Fecha de creación del registro en la base de datos']
  

  note: 'Tabla para registrar guías de remisión asociadas a órdenes de compra'
}


Table referral_guides_items {
  id unsignedbigint [primary key, increment]
  referral_guide_id unsignedbigint [note: 'Referencia a la tabla purchase_referral_guides']
  product_id unsignedbigint [note: 'Referencia a la tabla products']
  quantity decimal(10,2) [note: 'Cantidad de producto en la guía de remisión']
  gross_weight decimal(10,2) [null, note: 'Peso bruto del producto (kg)']
  net_weight decimal(10,2) [null, note: 'Peso neto del producto (kg)']
  net_amount decimal(12,2) [not null, note: 'Precio neto del producto sin impuestos']
  tax_amount decimal(12,2) [not null, note: 'Monto de impuestos aplicado al producto']
  total_amount decimal(12,2) [not null, note: 'Precio total del producto en la guía de remisión']
  created_at timestamp [note: 'Fecha de creación del registro en la base de datos']
}

// ---------------------------------------------------------
// 13. MANEJO DE DINERO
// ---------------------------------------------------------

Table accounts {
  id unsignedbigint [primary key, increment]
  name varchar(100) [note: 'Nombre de la cuenta (Ej: Caja Chica, Banco BBVA, etc.)']
  description varchar(255) [null, note: 'Descripción adicional de la cuenta']
  account_type enum('cash', 'bank', 'credit_card', 'other') [note: 'Tipo de cuenta']
  balance decimal(15,4) [default: 0, note: 'Saldo actual de la cuenta']
  created_at timestamp [note: 'Fecha de creación del registro en la base de datos']
  updated_at timestamp [note: 'Fecha de última actualización del registro en la base de datos']
}

Table transactions {
  id unsignedbigint [primary key, increment]
  
  // Dónde entra/sale el dinero (Caja Chica, BCP, Interbank)
  account_id unsignedbigint [note: 'Ref a accounts. Vital para saber el saldo.']
  
  // Qué tipo de movimiento es (Venta, Pago Prov, Gasto Luz)
  movement_type_id unsignedbigint [note: 'Ref a movement_types. Define si suma (+) o resta (-)']
  
  // Cómo se pagó (Efectivo, Visa, Yape)
  payment_method_id unsignedbigint [note: 'Ref a payment_methods']
  
  // Estado del dinero (Cobrado, Pendiente, Anulado)
  status enum('completed', 'pending', 'annulled', 'refunded') [default: 'completed']

  // 2. MONTOS Y FECHAS
 
  amount decimal(15,4) [note: 'El monto real que afecta el saldo contable.']
  operation_date timestamp [note: 'Fecha real del movimiento (puede ser distinta al created_at)']
  
  // Esto reemplaza a 'sale_order_id'. Permite pagar Ventas, Compras, Servicios, Prestamos...
  payable_type varchar(255) [null, note: 'Ej: App\\Models\\InvoiceSale, App\\Models\\InvoicePurchase']
  payable_id unsignedbigint [null, note: 'ID del documento asociado']

  // Solo se llenan si es pago en efectivo en mostrador
  amount_tendered decimal(15,4) [null, note: 'Solo Efectivo: Cuánto entregó el cliente (Ej: 50.00)']
  change_given decimal(15,4) [default: 0, note: 'Solo Efectivo: Vuelto entregado.']
  
  // Control de Turnos (Vital para cierre de caja)
  cash_register_shift_id unsignedbigint [null, note: 'Ref a shifts. Vincula este dinero a un turno de cajero especifico.']

  // Para transferencias o tarjetas
  operation_number varchar(100) [null, note: 'Nro Voucher, Operación Bancaria']
  payment_gateway_data json [null, note: 'Respuesta API Niubiz/Stripe: {auth: "123", card: "****4242"}']
  description varchar(255) [null, note: 'Observaciones manuales']

  // Reembolsos 
  parent_transaction_id unsignedbigint [null, note: 'Si es extorno, apunta a la transacción original']

  created_by unsignedbigint [not null, note:'Referencia a la tabla users, id del usuario que registro la transacción']
  created_at timestamp [not null, note:'Fecha de registro en la base de datos']
}




// ---------------------------------------------------------
// RELACIONES (FOREIGN KEYS)
// ---------------------------------------------------------

// PRODUCTOS
Ref: products.category_id > categories.id
Ref: products.unit_id > sunat_codes.id
Ref: categories.parent_id > categories.id
Ref: products.brand_id > brands.id
Ref: tax_product.product_id > products.id
Ref: tax_product.tax_id > sunat_codes.id

// STOCK SNAPSHOT
Ref: product_warehouse.product_id > products.id
Ref: product_warehouse.warehouse_id > warehouses.id

// KARDEX
Ref: kardex.product_id > products.id
Ref: kardex.warehouse_id > warehouses.id
Ref: kardex.movement_type_id > movement_types.id
Ref: kardex.created_by > users.id

// COMPRAS
Ref: purchase_orders.supplier_id > suppliers.id
Ref: purchase_orders.warehouse_id > warehouses.id
Ref: purchase_orders.created_by > users.id
Ref: purchase_items.purchase_order_id > purchase_orders.id
Ref: purchase_items.product_id > products.id
Ref: purchase_items.id < purchase_item_tax.purchase_item_id
Ref: purchase_item_tax.tax_id > sunat_codes.id

// VENTAS
Ref: sales_orders.customer_id > customers.id
Ref: sales_orders.warehouse_id > warehouses.id
Ref: sales_orders.created_by > users.id
Ref: sales_items.sales_order_id > sales_orders.id
Ref: sales_items.product_id > products.id
Ref: sales_origins.id < sales_orders.sale_origin_id

// TRANSFERENCIAS INTERNAS
Ref: internal_transfers_item.internal_transfer_id > internal_transfer_order.id 
Ref: internal_transfer_order.from_warehouse_id > warehouses.id
Ref: internal_transfer_order.to_warehouse_id > warehouses.id
Ref: internal_transfer_order.created_by > users.id

// AJUSTES DE INVENTARIO
Ref: inventory_adjustments.warehouse_id > warehouses.id
Ref: inventory_adjustments.created_by > users.id
Ref: inventory_adjustment_items.adjustment_id > inventory_adjustments.id
Ref: inventory_adjustment_items.product_id > products.id

// CAJAS REGISTRADORAS Y TURNOS
Ref: cash_registers.warehouse_id > warehouses.id
Ref: cash_register_shifts.cash_register_id > cash_registers.id
Ref: cash_register_shifts.user_id > users.id   

// CATALOGOS SUNAT
Ref: sunat_codes.sunat_catalog_id > sunat_catalogs.id

// MANEJO DE DINERO
Ref: transactions.account_id > accounts.id
Ref: transactions.payment_method_id > payment_methods.id
Ref: transactions.movement_type_id > movement_types.id
Ref: transactions.cash_register_shift_id > cash_register_shifts.id
Ref: transactions.parent_transaction_id > transactions.id
Ref: transactions.created_by > users.id